### PR TITLE
Add iOS/tvOS support

### PR DESCRIPTION
**Pull request by blacktm**

### CODE REVIEW

**Comment by andrewhavens** [comment]
Nice! 👍

**Comment by blacktm** [comment]
Whew! I think this is good to go.

@andrewhavens If you're feeling adventurous, feel free to give the branch a try:
1. `git clone --recursive https://github.com/simple2d/simple2d.git`
2. `cd simple2d` and `git checkout add-ios-tvos-support`
3. `make release` to build Apple frameworks
4. Open the iOS simulator, run `make ios` to build and run the triangle test app
5. In the simulator, switch the hardware device to tvOS, run `make tvos` to build and run the same app

**Comment by andrewhavens** [comment]
Awesome! 👍 I'll try it out later today.

**Comment by andrewhavens** [comment]
@blacktm I think there might be a bug in the instructions you gave me:

```
$ git clone --recursive https://github.com/simple2d/simple2d.git
Cloning into 'simple2d'...
remote: Counting objects: 1675, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 1675 (delta 15), reused 25 (delta 15), pack-reused 1645
Receiving objects: 100% (1675/1675), 435.24 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1058/1058), done.
Submodule 'deps' (https://github.com/simple2d/windows-deps.git) registered for path 'deps'
Submodule 'test/media' (https://github.com/simple2d/test_media.git) registered for path 'test/media'
Cloning into '.../simple2d/deps'...
remote: Counting objects: 182, done.        
remote: Total 182 (delta 0), reused 0 (delta 0), pack-reused 182        
Receiving objects: 100% (182/182), 7.50 MiB | 1.00 MiB/s, done.
Resolving deltas: 100% (58/58), done.
Cloning into '.../simple2d/test/media'...
remote: Counting objects: 41, done.        
remote: Total 41 (delta 0), reused 0 (delta 0), pack-reused 41        
Submodule path 'deps': checked out '39c037e25cdc6b836d07cfe794d79a512f8e696c'
Submodule path 'test/media': checked out 'fd57d1c22c11b1cc84b160236718b7e26c438a36'

$ cd simple2d

$ git checkout add-ios-tvos-support
M	deps
Branch add-ios-tvos-support set up to track remote branch add-ios-tvos-support from origin.
Switched to a new branch 'add-ios-tvos-support'

$ git status
On branch add-ios-tvos-support
Your branch is up-to-date with 'origin/add-ios-tvos-support'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   deps (new commits)

$ make release
# ...
==> Building iOS and tvOS release

cp -R deps/xcode/Simple2D.xcodeproj build
cp: deps/xcode/Simple2D.xcodeproj: No such file or directory
make: *** [release] Error 1
```

**Comment by blacktm** [comment]
Ah, maybe you have to run...
```
git submodule init
git submodule update --remote
```
...in the branch to get the new sub module contents.

**Comment by andrewhavens** [comment]
@blacktm By the way, I tried it again yesterday, using the new instructions and it worked! Really nice "build and launch simulator" experience!

**Comment by blacktm** [comment]
Great to hear — thanks for giving it a go! Good to know about the submodule init/updating for future testing. Tried to make it super simple, so I'm glad you also liked the simulator experience! Took me quite a while to figure out all the `xcrun simctl install/launch booted` automation stuff. Apparently you can do `open -a Simulator --args -CurrentDeviceUDID <UDID>` to open a specific simulator, but you have to know the UDID in advance (wish I could choose "iPhone 7" instead). Another issue is that the simulator opens asynchronously, so the `open` command finishes before the simulator starts, and `xcrun simctl` returns "no simulator available", ugh. Wonder how RubyMotion handles all this 🤔

**Comment by blacktm** [comment]
Looks like [Fastlane](https://fastlane.tools) is written in Ruby and has figured all this stuff out. Might have to borrow stuff from [`device_manager.rb`](https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/device_manager.rb)

**Comment by blacktm** [comment]
Well, I figured out the UDID and asyc simulator opening issues, and went a little crazy creating an all new `simulator` command and enhancing the `build` command for Xcode projects in https://github.com/simple2d/simple2d/pull/61/commits/68c6734ca505d9406baa7b06cc488e2c82b2af0e. See the [`simulator`](https://github.com/simple2d/simple2d/pull/61/commits/68c6734ca505d9406baa7b06cc488e2c82b2af0e#diff-2203959ba5685b119d845918cebf5a8fR1023) and [`build`](https://github.com/simple2d/simple2d/pull/61/commits/68c6734ca505d9406baa7b06cc488e2c82b2af0e#diff-2203959ba5685b119d845918cebf5a8fR1001) command usage. So much fun automating this stuff!

**Pull request merged**
