### PR TITLE
Update Makefile for Pi2

### PR DESCRIPTION
**Pull request by ukscone**
Fix build failure on Pi2

### CODE REVIEW

**Comment by blacktm** [comment]
@ukscone Thanks for the PR! I ended up just looking for `arm` in the `uname` string (see d4a90d4), since the includes will be the same for the RPI 1 & 2.

**Comment by ukscone** [comment]
makes sense. I just bunged in the extra lines to solve an immediate problem with the build instead of thinking about the "correct" way to do it

**Comment by blacktm** [comment]
@ukscone They're definitely both correct. I'm still on the lookout for a reliable way to detect the RPI and distinguish from other ARM platforms, so if you have any ideas, let me know!

**Comment by ukscone** [comment]
grep the Hardware line in /proc/cpuinfo maybe?

grep  Hardware /proc/cpuinfo | awk '{print $3}'

on Pi B/B+/A/A+ it'd be BCM2708 (iirc as no powered B/B+ atm)

on Pi2 it'd be BCM2709

**Comment by blacktm** [comment]
@ukscone Thanks for the ideas! Since platform detection could be more robust generally, I created a new issue (see #14).

**Pull request closed without merging**
