### PR TITLE
Exponential Moving Average for Fps

### PR DESCRIPTION
**Pull request by Dolphindalt**
#71

### CODE REVIEW

**Comment by blacktm** [comment]
Thanks for taking the initiative on this! Gave it a try and noticed the results are similar to the original implementation, I think because `new_fps` here is the same "number of frames from the beginning of time" rather than the "total number of frames in the last second". If we figure that that out, I think it should work.

**Comment by Dolphindalt** [comment]
Understood, will investigate this further.

**Comment by Dolphindalt** [comment]
With this, frames are counted until a second has passed and those are then multiplied in the simplified equation as frames in the last second to attain the the moving fps. Frames stays a small number, in contrast to the system before.

The ALPHA value can be tweaked so that fps averages can change faster. To test this, try changing the initial fps value from 60 to 30, and watch the fps slowly recover. The speed of said recovery is controlled by the ALPHA value.

I have noticed that elapsed_ms is now not used in the fps calculation and that it is unused throughout the program, but because it is a member of the S2D Window struct, I did not remove it in fear that it may be implemented in user's programs.

**Comment by blacktm** [comment]
Awesome, works great! Just made a couple tweaks, if that's alright. Namely:
- Lowered the `ALPHA` to `0.5`. I tested this with an `SDL_Delay(100)` in the update loop, and it decays from 60 FPS to 10 in about 7 seconds, which feels fast enough to be an accurate current reading, but long enough to get a smooth transition.
- Renamed `ALPHA` to `decay_rate` for a bit more clarity about what this value is.
- Reverted the submodule update, since it's not dependent here.
- Kept `frames` as is (total number of frames produced) and added a new variable `frames_last_sec` for the FPS calculation.
- Made the initial FPS guess be `window->fps_cap`, which is what the loop is trying to achieve as a frame rate.
- I also left the `elapsed_ms` in, since it can be useful for user apps to read that value.

😅 Whew, who knew a simple FPS calculation could be so complex! I'll give you a chance to review, but looks good to merge to me.

**Comment by Dolphindalt** [comment]
Everything looks well. There was one line from what I wrote that was bothering me, so I changed it so that we would not need to add 1000 to last_second_ms every time a loop occurs. last_second_ms is now next_second_ms because when we take SDL_GetTicks(), we add 1000 so we do not need to add it in the loop. Thanks for taking the time to review this merge with me. Hope to contribute more in the future.

**Comment by blacktm** [comment]
Nice, merged! Thanks again for tackling this, and hope you do contribute again.

**Pull request merged**
