### PR TITLE
Add mouse events, simplify input event structure

### PR DESCRIPTION
**Pull request by blacktm**

### CODE REVIEW

**Comment by KillaPL** [comment]
@blacktm Does this allow catching scrolling events?

**Comment by KillaPL** [comment]
@blacktm What also came to my mind is, can we also add on_mouse_move event? This would make it very nice and performant to implement things like `Button#on_hover` actions.

**Comment by blacktm** [comment]
It doesn't, but I see there's an [`SDL_MouseWheelEvent`](https://wiki.libsdl.org/SDL_MouseWheelEvent), which I'm sure also captures trackpad scrolling. I'll give it a spin — ha!

And yes, there's also an [`SDL_MouseMotionEvent`](https://wiki.libsdl.org/SDL_MouseMotionEvent) where we can get the `x, y` mouse position for the event. Would the relative `x` and `y` also be helpful? It also has button state in there, but I can't think of a scenario when those would be useful.

**Comment by KillaPL** [comment]
I'm not sure how I should understand relative `x` and `y`. Is that those same values that I can get by `get(:mouse_x)` and `get(:mouse_y)` ? This is what I'm thinking about.

And if you want me to review, please don't hold the merge, I can't be any helpful with c code, only when we get to ruby part I can do a real sit on this.

**Comment by blacktm** [comment]
Difference between the last x, y position. SDL uses the term "relative," but I think "delta" is probably better, more descriptive. Plus it's what [browsers are using](https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent/deltaX). I'll change that for both mouse motion and scrolling, keeping `x` and `y` for actual mouse positions, when applicable.

Oh, and I was just keeping these PRs open for a bit to let them evolve as we figure out Ruby API needs.

**Comment by KillaPL** [comment]
`delta_x` and `delta_y` are better names, indeed. So on mouse motion even there would be both deltas and current positions?

**Comment by blacktm** [comment]
Yes, I can get mouse move deltas both natively and on the web. Not exactly sure the use case for using them, but easy enough to include them.

**Comment by blacktm** [comment]
I think this is as good as it's going to get. Merging!

**Pull request merged**
